name: Native WebGPU Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Build Folder
        uses: actions/cache@v4
        with:
          path: lib/dawn  # The folder you want to cache (e.g., build, dist, bin)
          key: ${{ runner.os }}-build-${{ hashFiles('lib/fetch_dawn.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build and run
        run: |
          cd test
          rm -rf build
          ./build_and_run

